version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=whatsapp_service
      - MYSQL_USER=whatsapp_user
      - MYSQL_PASSWORD=whatsapp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # WhatsApp Event Service (Spring Boot)
  whatsapp-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - GPT4ALL_API_URL=http://gpt4all:8000
      - DB_URL=jdbc:mysql://mysql:3306/whatsapp_service
      - DB_USER=whatsapp_user
      - DB_PASSWORD=whatsapp_password
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      gpt4all:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # GPT4All Service
  gpt4all:
    image: gpt4all/gpt4all:latest
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=gpt4all-j
      - MAX_TOKENS=200
      - TEMPERATURE=0.3
    volumes:
      - gpt4all_models:/root/.cache/gpt4all
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whatsapp-service
    restart: unless-stopped
    profiles:
      - production

volumes:
  mysql_data:
    driver: local
  gpt4all_models:
    driver: local

networks:
  default:
    name: whatsapp-event-network
