server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: whatsapp-event-service
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/whatsapp_service}
    username: ${DB_USER:whatsapp_user}
    password: ${DB_PASSWORD:whatsapp_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

# WhatsApp Configuration
whatsapp:
  access-token: ${WHATSAPP_ACCESS_TOKEN:}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:}
  verify-token: ${VERIFY_TOKEN:mywhatsappverify}
  api-url: ${WHATSAPP_API_URL:https://graph.facebook.com/v21.0}

# AI Configuration
ai:
  gpt4all:
    api-url: ${GPT4ALL_API_URL:http://localhost:8000}
    timeout: 30000
    max-tokens: 200
    temperature: 0.3

# Logging Configuration
logging:
  level:
    com.whatsapp.eventservice: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Application Info
info:
  app:
    name: WhatsApp Event Service
    description: WhatsApp conversational service for local event discovery
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}
