# Docker-specific configuration
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/whatsapp_service
    username: whatsapp_user
    password: whatsapp_password
    
  jpa:
    hibernate:
      ddl-auto: update  # Allow schema updates in Docker
    
logging:
  level:
    com.whatsapp.eventservice: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
