openapi: 3.0.3
info:
  title: Discovery Assistant API
  version: 1.0.0
  description: API for event, business, and offer discovery with conversational AI support

servers:
  - url: https://api.yourdomain.com/v1

paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    get:
      summary: List all users
      responses:
        '200':
          description: Array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /conversations:
    post:
      summary: Start a new conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
      responses:
        '201':
          description: Conversation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

    get:
      summary: List all conversations
      responses:
        '200':
          description: Array of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}/messages:
    post:
      summary: Send a message and get system response
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sender
                - content
              properties:
                sender:
                  type: string
                  enum: [user, system]
                content:
                  type: string
      responses:
        '201':
          description: System response with suggested items
          content:
            application/json:
              schema:
                type: object
                properties:
                  system_message:
                    $ref: '#/components/schemas/Message'
                  suggested_items:
                    type: array
                    items:
                      $ref: '#/components/schemas/SuggestedItem'

  /events:
    get:
      summary: List all events
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

  /businesses:
    get:
      summary: List all businesses
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Business'
    post:
      summary: Create a new business
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Business'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'

  /offers:
    get:
      summary: List all offers
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
    post:
      summary: Create a new offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Offer'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        phone_number:
          type: string
        email:
          type: string
        profile_pic_url:
          type: string
        bio:
          type: string
        created_at:
          type: string
          format: date-time

    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time

    Business:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        phone_number:
          type: string
        email:
          type: string
        website_url:
          type: string
        address:
          type: string
        city:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        category_id:
          type: integer
        image_url:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Event:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        category_id:
          type: integer
        business_id:
          type: integer
        created_by:
          type: integer
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        location:
          type: string
        city:
          type: string
        image_url:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Offer:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        discount_code:
          type: string
        business_id:
          type: integer
        event_id:
          type: integer
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time

    Conversation:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        context_summary:
          type: string

    Message:
      type: object
      properties:
        id:
          type: integer
        conversation_id:
          type: integer
        sender:
          type: string
          enum: [user, system]
        content:
          type: string
        message_type:
          type: string
          enum: [text, image, audio, video, interactive]
        created_at:
          type: string
          format: date-time

    SuggestedItem:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum: [event, business, offer]
        item_id:
          type: integer
        title:
          type: string
        description:
          type: string
        link:
          type: string
